# Generated by Django 5.1.4 on 2025-01-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_analyticstemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='hide_title',
            field=models.BooleanField('Hide Title', default=False),
        ),
    ]
