# Generated by Django 5.1.7 on 2026-02-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_banner_hide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='message_author_format_sc',
            field=models.TextField(blank=True, verbose_name='Message author format'),
        ),
        migrations.AddField(
            model_name='topic',
            name='message_author_format_tc',
            field=models.TextField(blank=True, verbose_name='Message author format'),
        ),
        migrations.AddField(
            model_name='topic',
            name='message_author_label_sc',
            field=models.TextField(blank=True, verbose_name='Message author label'),
        ),
        migrations.AddField(
            model_name='topic',
            name='message_author_label_tc',
            field=models.TextField(blank=True, verbose_name='Message author label'),
        ),
    ]
