# Generated by Django 5.1.7 on 2026-02-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_banner_hide_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='show_author',
            field=models.BooleanField('Show Author', default=False),
        ),
    ]
