# Generated by Django 5.1.7 on 2026-02-27 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_topic_message_author_format_sc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='preview_sc',
        ),
        migrations.RemoveField(
            model_name='message',
            name='preview_tc',
        ),
    ]
