# Generated by Django 5.2.11 on 2026-09-06 11:31

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

def add_audio_all_field(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    Message = apps.get_model('app', 'Message')
    for message in Message.objects.all():
        if message.audio_tc and message.audio_tc.name and message.audio_sc and message.audio_sc.name and message.audio_tc.url == message.audio_sc.url:
            message.audio_all.name = message.audio_tc.name
            message.audio_tc = None
            message.audio_sc = None
            message.save(update_fields=['audio_all', 'audio_tc', 'audio_sc'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_message_preview_sc_remove_message_preview_tc'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_all',
            field=models.FileField(blank=True, upload_to='message/audio/', verbose_name='Audio (All)'),
        ),
        migrations.RunPython(add_audio_all_field),
    ]
