# Generated by Django 5.2.11 on 2026-09-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_message_audio_all'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytics',
        ),
        migrations.DeleteModel(
            name='AnalyticsTemp',
        ),
    ]
