# Generated by Django 5.2.11 on 2026-09-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_analytics_delete_analyticstemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='fingerprint',
        ),
    ]
