name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Set up docker context over SSH authentication
        shell: sh
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 "$SSH_HOST" > ~/.ssh/known_hosts
          docker context create remote --docker "host=ssh://$SSH_USERNAME@$SSH_HOST"
          ssh-agent -a 22
          echo "SSH_AUTH_SOCK=22" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV
          docker context use remote
        env:
          SSH_HOST: ${{ vars.WEB_DOMAIN }}
          SSH_USERNAME: ${{ vars.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Write .env files
        shell: sh
        run: |
          cd ./infrastructure/production
          touch .env
          touch .env.server
          echo ALLOWED_HOSTS=$ALLOWED_HOSTS >> .env
          echo SECRET_KEY=$SECRET_KEY >> .env
          echo CONTACT_EMAIL=$CONTACT_EMAIL >> .env
          echo BREVO_API_KEY=$BREVO_API_KEY >> .env
          echo CONTACT_FORM_TEMPLATE_ID=$CONTACT_FORM_TEMPLATE_ID >> .env
          echo CONTACT_FORM_RECIPIENTS=$CONTACT_FORM_RECIPIENTS >> .env
          echo S3_ENDPOINT_URL=$S3_ENDPOINT_URL >> .env
          echo S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID >> .env
          echo S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY >> .env
          echo S3_BUCKET_NAME=$S3_BUCKET_NAME >> .env
          echo S3_CUSTOM_DOMAIN=$S3_CUSTOM_DOMAIN >> .env
          echo WEB_DOMAIN=$WEB_DOMAIN >> .env.server
          echo WEB_HOST=$WEB_HOST >> .env.server
          echo WEB_URL=$WEB_URL >> .env.server
        env:
          ALLOWED_HOSTS: "${{ vars.ALLOWED_HOSTS }}"
          SECRET_KEY: "${{ secrets.SECRET_KEY }}"
          CONTACT_EMAIL: "${{ vars.CONTACT_EMAIL }}"
          BREVO_API_KEY: "${{ secrets.BREVO_API_KEY }}"
          CONTACT_FORM_TEMPLATE_ID: "${{ vars.CONTACT_FORM_TEMPLATE_ID }}"
          CONTACT_FORM_RECIPIENTS: "${{ secrets.CONTACT_FORM_RECIPIENTS }}"
          S3_ENDPOINT_URL: "${{ secrets.S3_ENDPOINT_URL }}"
          S3_ACCESS_KEY_ID: "${{ secrets.S3_ACCESS_KEY_ID }}"
          S3_SECRET_ACCESS_KEY: "${{ secrets.S3_SECRET_ACCESS_KEY }}"
          S3_BUCKET_NAME: "${{ vars.S3_BUCKET_NAME }}"
          S3_CUSTOM_DOMAIN: "${{ vars.S3_CUSTOM_DOMAIN }}"
          WEB_DOMAIN: "${{ vars.WEB_DOMAIN }}"
          WEB_HOST: "${{ vars.WEB_HOST }}"
          WEB_URL: "${{ vars.WEB_URL }}"

      - name: Deploy
        shell: sh
        run: docker compose -p lgweb -f ./infrastructure/production/docker-compose.yml up -d --build
